### PR TITLE
Shiqi

### PR DESCRIPTION
**Pull request by sychelsea0506**
@blue86321  in src/broker.py I add some functions to the message.

Message Persistence: Brokers may provide the functionality to persist messages to ensure durability. This can involve writing notes to disk or using a database for storing messages.

Message Filtering and Routing: Brokers can support advanced message filtering and routing mechanisms. This allows subscribers to specify criteria for the messages they are interested in receiving, such as filtering based on message content, metadata, or topic. The broker can then route the messages to the appropriate subscribers based on their preferences.

Message Transformation: Brokers may offer message transformation capabilities, allowing messages to be modified or enriched before they are delivered to subscribers. This can involve modifying content, adding metadata, or transforming messages into different formats.

These are just some functionality for decorating the message which will not effect the system. However I mentioned some of these functions in proposal , I write these functions

### CODE REVIEW

**Comment by sychelsea0506** [comment]
@blue86321  in src/test_cluster_dynamic_membership.py
I make the add node function usable in the terminal and the port number could be assigned by users. Same for del and stop all

**Comment by sychelsea0506** [comment]
@blue86321   in src/basic_node.py
I haven't checked your new commitment for node changes. I will check it later, but maybe we can use some of the primary nodes for tests in contrast to raft nodes to see the difference in performance.

**Comment by sychelsea0506** [comment]
> @blue86321 in src/basic_node.py I haven't checked your new commitment for node changes. I will check it later, but maybe we can use some of the primary nodes for tests in contrast to raft nodes to see the difference in performance.

like what I wrote in these file, this kind of node is not using consensus to do the vote and leader election, so we could use this to run  as a basic_test to compare with raft_nodes

**Comment by blue86321** [comment]
> @blue86321 in src/broker.py I add some functions to the message.
> 
> Message Persistence: Brokers may provide the functionality to persist messages to ensure durability. This can involve writing notes to disk or using a database for storing messages.
> 
> Message Filtering and Routing: Brokers can support advanced message filtering and routing mechanisms. This allows subscribers to specify criteria for the messages they are interested in receiving, such as filtering based on message content, metadata, or topic. The broker can then route the messages to the appropriate subscribers based on their preferences.
> 
> Message Transformation: Brokers may offer message transformation capabilities, allowing messages to be modified or enriched before they are delivered to subscribers. This can involve modifying content, adding metadata, or transforming messages into different formats.
> 
> These are just some functionality for decorating the message which will not effect the system. However I mentioned some of these functions in proposal , I write these functions

`Message Persistence` is the same as a node's `topic_subscribers` variable. I don't store to a file or a database in this demo, but the idea is the same.

Other functions look fine for me, but if you add these features, we'd better have a test/demo to show it. As for this project, I think these features are trivial.

**Comment by sychelsea0506** [comment]
关于那个多个cluster的想法，是这样的，我们现在是在一个ip地址下，然后可能就是说可以。1-10 port 属于一个cluster然后。20-30 port 属于另外的cluster这样，他们处理的是不用的 publisher和subscriber 我觉得这个是合理的scenario？ 就是为了说证明一个我们的 fault tolerance。我们是可以容纳好几个cluster一起运行的这样？

**Comment by blue86321** [comment]
> @blue86321 in src/test_cluster_dynamic_membership.py I make the add node function usable in the terminal and the port number could be assigned by users. Same for del and stop all

This one is fine. However, we need to keep an example to let others run it without any other input.
This feature is okay for our live demo in class. But it is not ideal in the `test` part. Probably it is better to add another file. We can use it to demo in class

**Comment by blue86321** [comment]
> > @blue86321 in src/basic_node.py I haven't checked your new commitment for node changes. I will check it later, but maybe we can use some of the primary nodes for tests in contrast to raft nodes to see the difference in performance.
> 
> like what I wrote in these file, this kind of node is not using consensus to do the vote and leader election, so we could use this to run as a basic_test to compare with raft_nodes

Good idea. But do you mean we need another `basic` without `raft`? It means we need to implement another version of `message broker`...  🫠

**Comment by sychelsea0506** [comment]
> Yes, or do you have other options for the performance comparison? I might simply implement the leader election functionality and write some tests to do the comparison, that will be fine, and we could make this experiment snapshot shown in our report., That is my idea

**Comment by blue86321** [comment]
> 关于那个多个cluster的想法，是这样的，我们现在是在一个ip地址下，然后可能就是说可以。1-10 port 属于一个cluster然后。20-30 port 属于另外的cluster这样，他们处理的是不用的 publisher和subscriber 我觉得这个是合理的scenario？ 就是为了说证明一个我们的 fault tolerance。我们是可以容纳好几个cluster一起运行的这样？

你搞错 fault tolerance 跟 cluster 的意义了。一个 cluster 包含多个 nodes，实践上天然就必须 fault tolerant，所以在 `test_cluster_false_tolerant.py` 中演示了一个 leader 挂了马上有另一个补上。相似的，任一 node 挂了都无所谓，整个 cluster 是 fault tolerant 的。

在实践上，不同 cluster 是不同的业务含义，没有叫做跨 cluster 的 fault tolerant，不同 cluster 就不是一个东西了。
例如 订单的集群、搜索的集群，他们自己各自 fault tolenrant，整个 application 就是高可用的。不会说订单+搜索一起 fault tolerant

**Comment by sychelsea0506** [comment]
> 关于那个多个cluster的想法，是这样的，我们现在是在一个ip地址下，然后可能就是说可以。1-10 port 属于一个cluster然后。20-30 port 属于另外的cluster这样，他们处理的是不用的 publisher和subscriber 我觉得这个是合理的scenario？ 就是为了说证明一个我们的 fault tolerance。我们是可以容纳好几个cluster一起运行的这样？

然后在cluster 的命名部分，我们可以让master在initialize的时候like 制定一个字母什么的，作为所有cluster的名字的前缀，只有知道这个前缀的人才能往这个里面add 或者 del node，这样还可以保证我们的系统的安全性，因为我们目前是都在localhost 但是如果需要多个ip的话我可以拿到我们实验室机房去做实验，这是没有问题的，当然这个就是一个想法，如果不想写那么多也可以就算了，只是作为一个讨论这样子

**Comment by sychelsea0506** [comment]
> > 关于那个多个cluster的想法，是这样的，我们现在是在一个ip地址下，然后可能就是说可以。1-10 port 属于一个cluster然后。20-30 port 属于另外的cluster这样，他们处理的是不用的 publisher和subscriber 我觉得这个是合理的scenario？ 就是为了说证明一个我们的 fault tolerance。我们是可以容纳好几个cluster一起运行的这样？
> 
> 你搞错 fault tolerance 跟 cluster 的意义了。一个 cluster 包含多个 nodes，实践上天然就必须 fault tolerant，所以在 `test_cluster_false_tolerant.py` 中演示了一个 leader 挂了马上有另一个补上。相似的，任一 node 挂了都无所谓，整个 cluster 是 fault tolerant 的。
> 
> 在实践上，不同 cluster 是不同的业务含义，没有叫做跨 cluster 的 fault tolerant，不同 cluster 就不是一个东西了。 例如 订单的集群、搜索的集群，他们自己各自 fault tolenrant，整个 application 就是高可用的。不会说订单+搜索一起 fault tolerant

oh 我明白了，那我这里可能是想表达scalabiliy的问题？

**Comment by sychelsea0506** [comment]
> > 关于那个多个cluster的想法，是这样的，我们现在是在一个ip地址下，然后可能就是说可以。1-10 port 属于一个cluster然后。20-30 port 属于另外的cluster这样，他们处理的是不用的 publisher和subscriber 我觉得这个是合理的scenario？ 就是为了说证明一个我们的 fault tolerance。我们是可以容纳好几个cluster一起运行的这样？
> 
> 你搞错 fault tolerance 跟 cluster 的意义了。一个 cluster 包含多个 nodes，实践上天然就必须 fault tolerant，所以在 `test_cluster_false_tolerant.py` 中演示了一个 leader 挂了马上有另一个补上。相似的，任一 node 挂了都无所谓，整个 cluster 是 fault tolerant 的。
> 
> 在实践上，不同 cluster 是不同的业务含义，没有叫做跨 cluster 的 fault tolerant，不同 cluster 就不是一个东西了。 例如 订单的集群、搜索的集群，他们自己各自 fault tolenrant，整个 application 就是高可用的。不会说订单+搜索一起 fault tolerant

我就是，like说把能想到的跟你讨论一下，我们可以不写那么复杂

**Comment by blue86321** [comment]
> Yes, or do you have other options for the performance comparison? I might simply implement the leader election functionality and write some tests to do the comparison, that will be fine, and we could make this experiment snapshot shown in our report., That is my idea

Just One node in the cluster is enough.
- publish has no performance issue since any node can respond to the request.
- un/subscribe would have performance issues if there are multiple nodes in the cluster since `leader` needs to notify all nodes, get majority `ACK`, and so on.

**If there is only one node in the cluster, the performance is the same as basic implementation** because there is no need to communicate with `followers`

To show how we address the performance issue, I think we can compare different nodes in the cluster (e.g. 1, 3, 10, 30) and their performance on handling un/subscribe requests or `join_cluster` requests.

I think the time complexity is nearly constant because we use multi-thread to send all these requests.

**Comment by blue86321** [comment]
> > 关于那个多个cluster的想法，是这样的，我们现在是在一个ip地址下，然后可能就是说可以。1-10 port 属于一个cluster然后。20-30 port 属于另外的cluster这样，他们处理的是不用的 publisher和subscriber 我觉得这个是合理的scenario？ 就是为了说证明一个我们的 fault tolerance。我们是可以容纳好几个cluster一起运行的这样？
> 
> 然后在cluster 的命名部分，我们可以让master在initialize的时候like 制定一个字母什么的，作为所有cluster的名字的前缀，只有知道这个前缀的人才能往这个里面add 或者 del node，这样还可以保证我们的系统的安全性，因为我们目前是都在localhost 但是如果需要多个ip的话我可以拿到我们实验室机房去做实验，这是没有问题的，当然这个就是一个想法，如果不想写那么多也可以就算了，只是作为一个讨论这样子

我投降  🫠   不想再写了，重点放在 distributed system 吧

**Comment by blue86321** [comment]
btw  能看完我代码再改我也是佩服，我觉得我这代码超烂，自己看都会晕的那种。后来 refactor 应该好一点。。。吧

**Comment by sychelsea0506** [comment]
ok， 那我就把目前你同意的部分，写完commit
（外层的封装+terminal add + del nodes 然后就是 commits的部分）
然后我再来思考一下关于performance的问题，有想法再跟你说这样？

**Comment by sychelsea0506** [comment]
> btw 能看完我代码再改我也是佩服，我觉得我这代码超烂，自己看都会晕的那种。后来 refactor 应该好一点。。。吧

这都做不到，那真划水怪了，我之前确实是家里出了点事回去了不然也不能让你自个儿写完是吧，我刚看refactor的部分确实清晰了很多嘿嘿

**Comment by blue86321** [comment]
> 

可以，建议新开个 file 之后 demo 用。到时候 demo 我们可以分着讲

**Pull request closed without merging**
